### PR TITLE
Add line to substitute "+" for space to fix search and fix

### PR DESCRIPTION
**Pull request by elserj**
geneontology/amigo#585

### CODE REVIEW

**Comment by elserj** [comment]
I just tested your solution on our dev site, it works, but seems to add a bunch of extra "+" chars to the filter box.
http://dev.planteome.org/amigo/search/ontology?q=plant%20cell
Note how it changed it to "plant+++cell".

**Comment by kltm** [comment]
@elserj You have the correct solution then! Give us a PR and we'll take it.
(I'll add a comment on your PR to tie it back to this ticket.)

**Comment by elserj** [comment]
Not sure what you mean, this is a PR...
https://github.com/geneontology/amigo/pull/592

**Comment by kltm** [comment]
Yes, sorry. Can you make a branch on ours? I cannot make modifications as this is from your fork...I think. All I'm looking for is the text: 
```perl
## NOTE: This is a local fix for bookmarking in https://github.com/geneontology/amigo/issues/585 .
```

**Comment by kltm** [comment]
And, by the way, thank you for all of this work!

**Comment by elserj** [comment]
I did reference the ticket in the commit message, but if the correct method for this is to create my own branch on your repo and use that specific text, I can do that.

**Comment by elserj** [comment]
Oh, doesn't look like I have rights to create my own branch in your repo anyway, unless I am missing something.

**Comment by elserj** [comment]
I did add you as a contributor to my fork, so you should be able to make changes there if you want now as well.

**Comment by kltm** [comment]
@elserj Got it--thanks!

**Pull request merged**
