### PR TITLE
Refresh JS build system

### LINKED ISSUE #676: Refresh the build system in AmiGO to better support modern JS/widgetry
Following on from https://github.com/geneontology/amigo/issues/650, we want to make sure that AmiGO is able to continue to be developed and support the addition of more modern JS and widgets, short of a complete rewrite and hopefully supprting the current (eco)system.

Tagging @vanaukenk and @ukemi

### PR DESCRIPTION
**Pull request by pkalita-lbl**
The changes here:

* Upgrade to the latest major version of gulp. 
  * Using `gulp.task` is no longer the preferred way of [defining a task](https://gulpjs.com/docs/en/getting-started/creating-tasks). Instead you simply define functions with various asynchronous completion mechanisms (returning streams, promises, etc) and export them from the module to register them with gulp.
  * Task dependencies as string arrays have been removed in favor of composing tasks with [`series`](https://gulpjs.com/docs/en/api/series) and [`parallel`](https://gulpjs.com/docs/en/api/parallel).
* Update gulp plugins
  * `gulp-shell` is discouraged by gulp because it encourages bad practices. It's fairly easy to replace it with calls to functions in Node's `child_process` module. I've wrapped those calls into a new `shell` function that tasks can use.
  * I removed several gulp plugins that were not being used anywhere.
* Add Babel to JS compile pipeline. This uses `@babel/preset-env`  to enable a baseline set of the latest JS features, including ES modules. Additional Babel plugins and configuration can be done here as needed in the future.
* Some light reformatting of the gulpfile to be more inline with standard JS styling.

Fixes #676

### CODE REVIEW

**Comment by kltm** [comment]
@pkalita-lbl Okay, testing locally with `sjcarbon@moiraine:~/local/src/git/amigo[issue-676]$:) ./node_modules/.bin/gulp build`

The sub-command `cd ./javascript/npm/amigo2-instance-data && npm install` gives me the error:

```
ERROR:
Pinged: https://s3-us-west-1.amazonaws.com/go-amigo-usage-master/ping.json
/home/sjcarbon/local/src/git/amigo/javascript/npm/amigo2-instance-data/node_modules/npm/lib/utils/exit-handler.js:22
  const hasLoadedNpm = npm?.config.loaded
                           ^

SyntaxError: Unexpected token .
```

I suspect that you need to do to that sub-package what you did for in the mail package. If you'd like, and you have tylenol/whiskey available, I can walk you through *why* this aberration exists in the first place.

It could also be that I'm messing something else up at my end. Let me know if there is something else I should be doing.

**Comment by pkalita-lbl** [comment]
Hmm I don't see the same error while working in the `amig-standalone` container. It smells like some kind of version mismatch issue though. It's complaining about an optional chaining operator (`?.`). That was implemented in Node.js 14.0.0, and we're using Node.js 8.x (at least in the container). So for some reason your version of the `npm` package in `amigo2-instance-data` must be way ahead of where it should be. We should probably just meet to work through it instead of going back and forth in GItHub comments.

**Comment by kltm** [comment]
@pkalita-lbl After some cleaning locally, this worked for me in a non-docker environment, so I think this is good. 

What do you think about updating the `amigo-standalone` image with newer code? I think we can punt on that until there is something "production-worth" to add, but it might help in your development?

Later on, we'll want to coordinate with @abessiari about getting this out to the production devops images.

**Review by kltm — APPROVED** [review]
A big improvement; all testing has worked fine so far.

**Comment by pkalita-lbl** [comment]
> What do you think about updating the amigo-standalone image with newer code? I think we can punt on that until there is something "production-worth" to add, but it might help in your development?

I don't think it matters too much one way or the other for the development workflow I'm using, but I'd be happy to nonetheless. Maybe that's something to take on once more of the actual AmiGO UI work is done? 

> Later on, we'll want to coordinate with @abessiari about getting this out to the production devops images.

Yeah, please loop me in. I'm curious how all that works.

**Pull request merged**
