### PR TITLE
handling production and development mode. 

### PR DESCRIPTION
**Pull request by abessiari**
- Handling production mode by allowing for the download of solr index,  golr_timestamp.log, release-archive-doi.json. 
- Handling dev mode and allowing for creating of solr index ...

### CODE REVIEW

**Comment by abessiari** [comment]
@kltm 

Now supporting prod/dev mode. prod is the default.

**Comment by kltm** [comment]
Successful local with:

```diff
diff --git a/provision/vars.yaml b/provision/vars.yaml
index ce59e9db..aa22d8f6 100644
--- a/provision/vars.yaml
+++ b/provision/vars.yaml
@@ -3,13 +3,13 @@
 # Point stage_dir to a different locatiom. By default it will reside in the cur
rent directory.
 ##############
 stage_dir: "{{ lookup('env', 'PWD') }}/stage_dir"
-branch: master
+branch: provision2
 tag: latest
-repo: https://github.com/geneontology/amigo.git
+repo: https://github.com/abessiari/amigo.git
 repo_dir: '{{ stage_dir }}/amigo'
```

```
mkdir -p /tmp/stage && ansible-playbook -e "stage_dir=/tmp/stage" -u ubuntu -i "localhost," --connection=local build_image.yaml
mkdir -p /tmp/stage/srv-solr-data/index/ && cd /tmp/stage/srv-solr-data/index/
wget http://skyhook.berkeleybop.org/issue-35-neo-test/products/solr/golr-index-contents.tgz
tar -zxvf golr-index-contents.tgz
(back to amigo/provision)
ansible-playbook -e "stage_dir=/tmp/stage" -u ubuntu -i "localhost," --connection=local stage.yaml
```

**Comment by kltm** [comment]
Going through PROVISION_AWS_README.md, when reaching
`ansible-playbook -e "stage_dir=$STAGE_DIR" -u ubuntu -i "$HOST," --private-key $PRIVATE_KEY build_image.yaml`
I had failure with 
```
fatal: [52.5.59.113]: FAILED! => {"changed": false, "module_stderr": "/home/sjcarbon/.ssh/config line 3: Unsupported option \"rsaauthentication\"\r\nShared connection to 52.5.59.113 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 127}
```
I was passed after performing `sudo apt-get -u install python` on the recently terraform-created target machine; this could possibly be automated or added to a new base image?

**Comment by kltm** [comment]
Looking at how things are handled in the "Untar index archive" step, I would suggest an alternate explicit command that can run much much faster, especially as this is likely the most time-consuming step: https://github.com/geneontology/operations/blob/ffb158c89a9198811c6139801a63866b3fa15f35/ansible/roles/update-golr-forced/tasks/main.yml#L46

**Comment by abessiari** [comment]
add install of python. 
add docker-compose -f in ansible. 
add ServerAlias .... 
tar -I pigz -xvf /srv/golr_new.tgz -C /srv/golr_unpacked

**Comment by kltm** [comment]
@abessiari Should we reopen and merge this, or were you wanting to start fresh with a new PR?

**Comment by abessiari** [comment]
Please go ahead and merge.

**Comment by kltm** [comment]
Merged!

**Comment by abessiari** [comment]
Thanks.

**Pull request merged**
