### PR TITLE
using shell command for docker compose

### PR DESCRIPTION
**Pull request by abessiari**
ansible docker-compose module needs the python interpreter to be set when doing local testing and to install docker-compose python module.  It is turning out to be a headache much like the ansible docker  module.

### CODE REVIEW

**Comment by abessiari** [comment]
@kltm 
Please merge if testing went well. Thanks.

**Comment by kltm** [comment]
Xref https://github.com/berkeleybop/bbops/issues/4

**Comment by kltm** [comment]
This does seem to be working for me locally. Merging.

**Comment by abessiari** [comment]
@kltm 

Great. I am available to meet before 1pm today  and after 4 pm if need be.

**Pull request merged**
