### PR TITLE
Modify bin/amigo.js to allow more than 1000 parameters.  Set it to 10…

### PR DESCRIPTION
**Pull request by elserj**
…0000 and 50mb.

This fixes an issue in planteome/amigo where the API fails if the request contains more than 1000 parameters.

### CODE REVIEW

**Comment by kltm** [comment]
@elserj This is to limit input from users? Have you run into some issue?

**Comment by elserj** [comment]
Yes, we would get a failure if the input list had more than 1000 parameters.  Tracked it down to the default of the body-parser.  This change ups it from the default to 100000, which should be plenty as I can't think of any species with more genes or an ontology with more terms that would be searched with the API.  I probably should have made an issue for this, but I was unsure where the problem was, ie. Apache, JS... until I fixed it.

**Comment by kltm** [comment]
Ah, so this is upping it. No problem there.

**Comment by kltm** [comment]
It would be good to catch exceptions generated from problems like this, but we can worry about that later (like when we start using this API as the JS backend for AmiGO, replacing the perl parts).

**Pull request merged**
