### PR TITLE
added monit to golr container and log rotation monit, of amigo logs and golr jetty process

### PR DESCRIPTION
**Pull request by abessiari**
- added monit to golr container and tested by kill java process. 
- log rotation for jetty process 
- log rotation for monit
- log rotation for jetty using console-capture.xml config file
- log rotation for apache running inside amigo container
- setting init to true in docker compose otherwise we get defunct when killing child processes (daemons). Monit trips on this. 
- Reorganized stage_dir by adding amigo_configs and golr_configs 
- Tested using local and AWS deployment.

### CODE REVIEW

**Comment by abessiari** [comment]
@kltm 
Here is the initial PR for monit ....

**Comment by kltm** [comment]
Shall I take this PR now, or wait a little?
I'll go ahead and start testing now either way.

**Comment by abessiari** [comment]
> 

Up to you. It should be good to go.

**Comment by kltm** [comment]
I'll take it now, as it might make it easier to fiddle with the docs as I go through.

**Comment by kltm** [comment]
For https://github.com/berkeleybop/bbops/issues/4

**Pull request merged**
